include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    always_use_package_imports: ignore
    unreachable_switch_default: ignore 
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/generated/**"
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
   always_use_package_imports: ignore 