name: homecenter
description: "Homecenter test"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_bloc: ^9.1.1
  get_it: ^8.2.0

  # Utils
  equatable: ^2.0.7

  # Network
  dio: ^5.8.0+1
  http_cache_drift_store: ^7.0.0
  drift: ^2.28.1
  drift_flutter: ^0.2.5
  sqlite3_flutter_libs: ^0.5.39
  path: ^1.9.1
  json_annotation: ^4.9.0
  dio_cache_interceptor: ^4.0.3
  path_provider: ^2.1.5
  bloc_concurrency: ^0.3.0
  mocktail: ^1.0.4
  bloc_test: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lints
  flutter_lints: ^5.0.0
  very_good_analysis: ^9.0.0
  build_runner: ^2.6.0
  json_serializable: ^6.10.0
  drift_dev: ^2.28.1

flutter:
  uses-material-design: true
